version: "2"
issues:
  fix: true
linters:
  default: none
  enable:
    - govet
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - internal/examples
      - vendor
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
    - gofmt
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/pubgo/redant
    gofmt:
      simplify: false
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
        - pattern: 'a[b:len(a)]'
          replacement: 'a[b:]'

  exclusions:
    paths:
      - internal/examples
      - vendor
      - examples$
      - proto
