package completioncmd

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/pubgo/redant"
)

func New() *redant.Command {
	var shell string
	return &redant.Command{
		Use:   "completion [shell]",
		Short: "Generate the autocompletion script for the specified shell",
		Long: `Generate the autocompletion script for redant for the specified shell.
See each sub-command's help for details on how to use the generated script.`,
		Args: []redant.Arg{
			{
				Name:        "shell",
				Description: "shell for which the completion script is generated",
				Required:    true,
				Value:       redant.EnumOf(&shell, "bash", "zsh", "fish"),
			},
		},
		Handler: func(ctx context.Context, inv *redant.Invocation) error {
			if len(inv.Args) == 0 {
				if _, err := fmt.Fprintf(inv.Stderr, "error: shell argument is required. Available shells: bash, zsh, fish\n"); err != nil {
					return fmt.Errorf("write stderr: %w", err)
				}
				return fmt.Errorf("missing shell argument")
			}

			shell := inv.Args[0]
			switch shell {
			case "bash":
				return generateBashCompletion(ctx, inv)
			case "zsh":
				return generateZshCompletion(ctx, inv)
			case "fish":
				return generateFishCompletion(ctx, inv)
			default:
				if _, err := fmt.Fprintf(inv.Stderr, "error: unsupported shell: %s. Available shells: bash, zsh, fish\n", shell); err != nil {
					return fmt.Errorf("write stderr: %w", err)
				}
				return fmt.Errorf("unsupported shell: %s", shell)
			}
		},
	}
}

// generateBashCompletion generates bash completion script
func generateBashCompletion(ctx context.Context, inv *redant.Invocation) error {
	cmd := inv.Command.Parent() // Get the root command
	if cmd == nil {
		cmd = inv.Command
	}

	progName := filepath.Base(os.Args[0])

	// Header
	header := fmt.Sprintf(`#!/bin/bash

# %s completion for bash
# Autogenerated by redant

%s() {
    local cur prev opts cmd
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    # Command stack tracking
    local cmd_stack=()
    local i=1
    local found_cmd=false

    # Build command stack
    while [ $i -lt $COMP_CWORD ]; do
        cmd="${COMP_WORDS[$i]}"
        cmd_stack+=($cmd)
        i=$((i+1))
    done

    # Handle completion based on command stack
    case "${cmd_stack[@]}" in
`, progName, progName)

	// Generate command completions
	var commandsBuf bytes.Buffer
	generateBashCommandCompletions(cmd, "", &commandsBuf, progName)

	// Footer
	footer := fmt.Sprintf(`    *)
        COMPREPLY=()
        ;;
    esac
}

complete -F %s %s
`, progName, progName)

	// Write the full script
	if _, err := fmt.Fprint(inv.Stdout, header); err != nil {
		return err
	}
	if _, err := commandsBuf.WriteTo(inv.Stdout); err != nil {
		return err
	}
	if _, err := fmt.Fprint(inv.Stdout, footer); err != nil {
		return err
	}

	return nil
}

// generateBashCommandCompletions generates command completion for bash recursively
func generateBashCommandCompletions(cmd *redant.Command, indent string, buf *bytes.Buffer, progName string) {
	cmdName := cmd.Name()
	fullName := cmd.FullName()

	// Generate option completions for this command
	fmt.Fprintf(buf, `    %q)
        # Completions for %s
        local opts="--help "
`, fullName, cmdName)

	// Add all options
	for _, opt := range cmd.FullOptions() {
		if opt.Hidden {
			continue
		}
		if opt.Flag != "" {
			fmt.Fprintf(buf, "        opts+='--%s '\n", opt.Flag)
			if opt.Shorthand != "" {
				fmt.Fprintf(buf, "        opts+='-%s '\n", opt.Shorthand)
			}
		}
	}

	// Add subcommands
	if len(cmd.Children) > 0 {
		buf.WriteString("        local subcmds=\"")
		for _, child := range cmd.Children {
			if !child.Hidden {
				buf.WriteString(child.Name() + " ")
			}
		}
		buf.WriteString("\"\n")
		buf.WriteString("        COMPREPLY=( $(compgen -W \"$opts $subcmds\" -- \"$cur\") )")
	} else {
		buf.WriteString("        COMPREPLY=( $(compgen -W \"$opts\" -- \"$cur\") )")
	}

	buf.WriteString("\n        ;;")

	// Generate completions for subcommands
	for _, child := range cmd.Children {
		if !child.Hidden {
			generateBashCommandCompletions(child, indent+"    ", buf, progName)
		}
	}
}

// generateZshCompletion generates zsh completion script
func generateZshCompletion(ctx context.Context, inv *redant.Invocation) error {
	cmd := inv.Command.Parent() // Get the root command
	if cmd == nil {
		cmd = inv.Command
	}

	progName := filepath.Base(os.Args[0])
	funcName := "_" + progName

	// Header
	header := fmt.Sprintf(`#compdef %s
compdef %s %s

# %s completion for zsh
# Autogenerated by redant

%s() {
	local -a cmd_path options subcommands
	local word i

	for (( i = 2; i < CURRENT; i++ )); do
		word="${words[i]}"
		[[ -z "$word" ]] && continue
		[[ "$word" == "--" ]] && break
		[[ "$word" == -* ]] && continue
		cmd_path+=("$word")
	done

	local cmd_key="${(j: :)cmd_path}"
	case "$cmd_key" in
`, progName, funcName, progName, progName, funcName)

	// Generate command completions
	var commandsBuf bytes.Buffer
	generateZshCommandCases(cmd, nil, &commandsBuf)

	// Footer
	footer := `    esac

	if (( ${#subcommands[@]} > 0 )); then
		_describe 'subcommands' subcommands
	fi
	if (( ${#options[@]} > 0 )) && [[ "${words[CURRENT]}" == -* ]]; then
		_describe 'options' options
	fi
}
`

	// Write the full script
	if _, err := fmt.Fprint(inv.Stdout, header); err != nil {
		return err
	}
	if _, err := commandsBuf.WriteTo(inv.Stdout); err != nil {
		return err
	}
	if _, err := fmt.Fprint(inv.Stdout, footer); err != nil {
		return err
	}

	return nil
}

// generateZshCommandCases emits command-path based case branches for zsh completion.
func generateZshCommandCases(cmd *redant.Command, path []string, buf *bytes.Buffer) {
	caseKey := strings.Join(path, " ")
	buf.WriteString(fmt.Sprintf("        %q)\n", caseKey))

	buf.WriteString("            options=(\n")
	for _, opt := range cmd.FullOptions() {
		if opt.Hidden || opt.Flag == "" {
			continue
		}
		desc := optionZshDescription(opt)
		buf.WriteString(fmt.Sprintf("                '--%s:%s'\n", opt.Flag, desc))
		if opt.Shorthand != "" {
			buf.WriteString(fmt.Sprintf("                '-%s:%s'\n", opt.Shorthand, desc))
		}
	}
	buf.WriteString("            )\n")

	buf.WriteString("            subcommands=(\n")
	for _, child := range cmd.Children {
		if child.Hidden {
			continue
		}
		buf.WriteString(fmt.Sprintf("                '%s:%s'\n", child.Name(), escapeZshDescription(child.Short)))
	}
	buf.WriteString("            )\n")
	buf.WriteString("            ;;\n")

	for _, child := range cmd.Children {
		if child.Hidden {
			continue
		}
		generateZshCommandCases(child, append(path, child.Name()), buf)
	}
}

func escapeZshDescription(s string) string {
	s = strings.TrimSpace(s)
	s = strings.ReplaceAll(s, "'", "\\'")
	s = strings.ReplaceAll(s, ":", "\\:")
	return s
}

func optionZshDescription(opt redant.Option) string {
	desc := strings.TrimSpace(opt.Description)
	if desc == "" {
		desc = opt.Flag
	}
	return escapeZshDescription(desc)
}

// generateFishCompletion generates fish completion script
func generateFishCompletion(ctx context.Context, inv *redant.Invocation) error {
	cmd := inv.Command.Parent() // Get the root command
	if cmd == nil {
		cmd = inv.Command
	}

	progName := filepath.Base(os.Args[0])

	// Header
	header := fmt.Sprintf(`# %s completion for fish
# Autogenerated by redant

complete -c %s -n "__fish_use_subcommand" -a "completion" -d "Generate the autocompletion script for the specified shell"
`, progName, progName)

	// Generate command completions
	var commandsBuf bytes.Buffer
	generateFishCommandCompletions(cmd, &commandsBuf)

	// Write the full script
	if _, err := fmt.Fprint(inv.Stdout, header); err != nil {
		return err
	}
	if _, err := commandsBuf.WriteTo(inv.Stdout); err != nil {
		return err
	}

	return nil
}

// generateFishCommandCompletions generates command completion for fish recursively
func generateFishCommandCompletions(cmd *redant.Command, buf *bytes.Buffer) {
	cmdName := cmd.Name()
	fullCmdPath := cmd.FullName()
	cmdParts := strings.Split(fullCmdPath, " ")

	// Generate completions for this command's options
	for _, opt := range cmd.FullOptions() {
		if opt.Hidden {
			continue
		}

		var completeCmd string
		if len(cmdParts) > 1 {
			// Subcommand
			completeCmd = fmt.Sprintf("complete -c %s -n \"__fish_seen_subcommand_from %s\"", cmdParts[0], strings.Join(cmdParts[1:], " "))
		} else {
			// Root command
			completeCmd = fmt.Sprintf("complete -c %s", cmdName)
		}

		if opt.Shorthand != "" {
			completeCmd += fmt.Sprintf(" -s %s", opt.Shorthand)
		}

		completeCmd += fmt.Sprintf(" -l %s -d \"%s\"", opt.Flag, opt.Description)

		// Add value hint if applicable
		if opt.Type() != "bool" {
			completeCmd += fmt.Sprintf(" -r -f -a \"(__fish_complete_placeholder %s)\"", opt.Type())
		}

		buf.WriteString(completeCmd)
		buf.WriteString("\n")
	}

	// Generate completions for subcommands
	if len(cmd.Children) > 0 {
		for _, child := range cmd.Children {
			if !child.Hidden {
				fmt.Fprintf(buf, "complete -c %s -n \"__fish_seen_subcommand_from %s\" -a \"%s\" -d \"%s\"\n",
					cmdParts[0], strings.Join(cmdParts[1:], " "),
					child.Name(), child.Short)
			}
		}
	}

	// Recursively generate completions for subcommands
	for _, child := range cmd.Children {
		if !child.Hidden {
			generateFishCommandCompletions(child, buf)
		}
	}
}

// AddCompletionCommand adds the completion command to the root command
func AddCompletionCommand(rootCmd *redant.Command) {
	rootCmd.Children = append(rootCmd.Children, New())
}
